notlath/Guitara-Scheduling-System

- royal-care-frontend/src/components/scheduling/AvailabilityManager.jsx
> Fix layout of availability table by adjusting cell structure for better readability

- NOTIFICATIONS_FIX_SUMMARY.md
- REVIEW_REJECTION_FIX.md
- check_sqlite_direct.py
- debug_notifications.py
- guitara/scheduling/management/__init__.py
- guitara/scheduling/management/commands/__init__.py
- guitara/scheduling/management/commands/test_notifications.py
- guitara/scheduling/serializers.py
- guitara/scheduling/views.py
- royal-care-frontend/src/features/scheduling/schedulingSlice.js
- simple_notifications_test.py
- test_endpoint_directly.py
- test_notification_logic.py
- test_notifications.py
- test_notifications_endpoint.py
- test_review_payload.py
feat: Improve notification handling and rejection review process with enhanced error handling and debugging
> feat: Improve notification handling and rejection review process with enhanced error handling and debugging

- NOTIFICATIONS_FIX_SUMMARY.md
- REJECTION_FIX_SUMMARY.md
- REVIEW_REJECTION_FIX.md
- check_sqlite_direct.py
- debug_notifications.py
- guitara/scheduling/management/commands/test_notifications.py
- guitara/scheduling/views.py
- royal-care-frontend/src/features/scheduling/schedulingSlice.js
- simple_notifications_test.py
- test_endpoint_directly.py
- test_notification_logic.py
- test_notifications.py
- test_notifications_endpoint.py
- test_rejection_flow.py
- test_review_payload.py
- Improved the appointment acceptance and rejection flow in AppointmentViewSet.
- Enhanced error handling for rejection reasons, ensuring proper validation.
- Added detailed logging for debugging purposes throughout the appointment lifecycle.
- Updated the frontend scheduling slice to handle rejection and review actions more robustly.
- Refined test cases for notification and rejection flows, ensuring comprehensive coverage and clarity.
- Cleaned up code formatting for better readability and consistency across various files.
> Refactor appointment handling and notification logic

- NOTIFICATION_FEATURES_IMPLEMENTATION.md
- guitara/scheduling/views.py
- royal-care-frontend/src/components/scheduling/NotificationCenter.jsx
- royal-care-frontend/src/components/scheduling/SchedulingDashboard.jsx
- royal-care-frontend/src/features/scheduling/schedulingSlice.js
- royal-care-frontend/src/styles/NotificationCenter.css
- royal-care-frontend/src/styles/SchedulingDashboard.css
- test_notification_features.py
feat: Implement comprehensive notification management features including mark as unread, delete all, and delete read notifications
> feat: Implement comprehensive notification management features including mark as unread, delete all, and delete read notifications

- royal-care-frontend/src/components/scheduling/AvailabilityManager.jsx
feat: Refactor availability management to improve date handling and time slot generation
> feat: Refactor availability management to improve date handling and time slot generation

- royal-care-frontend/src/components/scheduling/AvailabilityManager.jsx
- royal-care-frontend/src/components/scheduling/Calendar.jsx
fix: Correct time slot generation and reset values in AvailabilityManager
> fix: Correct time slot generation and reset values in AvailabilityManager

- NOTIFICATION_SYSTEM_IMPROVEMENTS.md
- check_notifications.py
- create_test_notifications.py
- royal-care-frontend/src/components/scheduling/NotificationCenter.jsx
- royal-care-frontend/src/styles/NotificationCenter.css
feat: Enhance Notification Center UI and functionality with modern design and improved user interactions
> feat: Enhance Notification Center UI and functionality with modern design and improved user interactions

- AVAILABILITY_CREATION_FIX.md
- AVAILABILITY_DISPLAY_FIX.md
- LOADING_UX_IMPROVEMENTS.md
- NON_INTRUSIVE_LOADING_SUMMARY.md
- REACT_INFINITE_LOOP_FIX.md
- WEBSOCKET_FIX_SUMMARY.md
- create_test_user.py
- royal-care-frontend/src/App.jsx
- royal-care-frontend/src/components/OperatorDashboard.jsx
- royal-care-frontend/src/components/TherapistDashboard.jsx
- royal-care-frontend/src/components/scheduling/AvailabilityManager.jsx
- royal-care-frontend/src/components/scheduling/SchedulingDashboard.jsx
- royal-care-frontend/src/components/scheduling/WebSocketStatus.jsx
- royal-care-frontend/src/features/scheduling/schedulingSlice.js
- royal-care-frontend/src/services/webSocketService.js
- royal-care-frontend/src/styles/TherapistDashboard.css
- royal-care-frontend/src/styles/WebSocketStatus.css
- royal-care-frontend/src/utils/authFixer.js
- royal-care-frontend/src/utils/authUtils.js
- royal-care-frontend/src/utils/debugAuth.js
- royal-care-frontend/src/utils/tokenTest.js
- test_api.py
- test_availability_creation.py
- test_availability_display.py
- Refactored WebSocketStatus component for subtle status indicators and temporary notifications.
- Updated TherapistDashboard to handle background loading without visible spinners, enhancing user experience.
- Improved CSS for WebSocketStatus and TherapistDashboard for a modern look.
- Introduced a new auth utility for better error handling and debugging.
- Disabled WebSocket connections in dashboard components and replaced with polling for real-time updates.
- Created test scripts for user authentication and availability workflows.
- Fixed React infinite loop issues by simplifying useEffect dependencies.
- Enhanced availability display testing to ensure immediate visibility of newly created records.
> feat: Implement non-intrusive background loading and WebSocket fixes

- AUTO_RETRY_LOGIN_IMPLEMENTATION.md
- PROJECT_STATUS_COMPLETE.md
- guitara/authentication/views.py
- guitara/core/urls.py
- guitara/core/views.py
- royal-care-frontend/src/components/auth/DisabledAccountAlert.jsx
- royal-care-frontend/src/components/auth/DisabledAccountAlert.module.css
- royal-care-frontend/src/pages/LoginPage/LoginPage.jsx
- royal-care-frontend/src/services/auth.js
- test_auto_retry_login.py
Implement auto-retry login for re-enabled accounts; add account status polling and UI enhancements
> Implement auto-retry login for re-enabled accounts; add account status polling and UI enhancements

- LOGO_CLICK_IMPLEMENTATION_COMPLETE.md
- THERAPIST_DASHBOARD_ROUTING_FIX_COMPLETE.md
- royal-care-frontend/src/components/MainLayout.jsx
- royal-care-frontend/src/components/TherapistDashboard.jsx
- royal-care-frontend/src/components/auth/Login.jsx
- royal-care-frontend/src/components/auth/RouteHandler.jsx
- royal-care-frontend/src/pages/LoginPage/LoginPage.jsx
- test_logo_click_functionality.js
Implement role-based routing for dashboard navigation and fix login redirect logic
> Implement role-based routing for dashboard navigation and fix login redirect logic

- LOGO_CLICK_IMPLEMENTATION_COMPLETE.md
- THERAPIST_DASHBOARD_ROUTING_FIX_COMPLETE.md
- royal-care-frontend/src/components/auth/Login.jsx
- royal-care-frontend/src/pages/LoginPage/LoginPage.jsx
- test_logo_click_functionality.js
Refactor logo click functionality and login redirect logic for improved clarity and consistency
> Refactor logo click functionality and login redirect logic for improved clarity and consistency

- README.md
Update README.md to reflect recent improvements and archive organization changes
> Update README.md to reflect recent improvements and archive organization changes

- README.md
- start_all.bat
- start_development.py
Refactor development setup: replace start_all.bat with start_development.py for cross-platform support and improved automation
> Refactor development setup: replace start_all.bat with start_development.py for cross-platform support and improved automation

- README.md
Enhance README.md: Update installation instructions with automated setup script and troubleshooting tips
> Enhance README.md: Update installation instructions with automated setup script and troubleshooting tips

- README.md
Update README.md: Revise root directory description and enhance quick start script section for clarity
> Update README.md: Revise root directory description and enhance quick start script section for clarity

- royal-care-frontend/src/components/TherapistDashboard.jsx
- royal-care-frontend/src/components/common/LoadingComponents.css
- royal-care-frontend/src/components/common/LoadingComponents.jsx
- royal-care-frontend/src/components/scheduling/AppointmentForm.jsx
- royal-care-frontend/src/components/scheduling/AvailabilityManager.jsx
- royal-care-frontend/src/components/scheduling/SchedulingDashboard.jsx
Add enhanced loading components: spinners, buttons, overlays, and skeleton loaders
> Add enhanced loading components: spinners, buttons, overlays, and skeleton loaders

- royal-care-frontend/src/components/OperatorDashboard.jsx
Fix the AvailabilityManager component and update navigation logic in OperatorDashboard
> Fix the AvailabilityManager component and update navigation logic in OperatorDashboard

- royal-care-frontend/src/components/auth/Register.jsx
- royal-care-frontend/src/globals/FormField.css
- royal-care-frontend/src/globals/FormField.jsx
- royal-care-frontend/src/globals/theme.css
- royal-care-frontend/src/pages/LoginPage/LoginPage.module.css
Improve the registration form by using email instead of username, adding validation for input fields, and enhancing error handling. Adjust the positioning of error popups for better visibility and improve responsiveness on smaller screens. Refactor the password field to include a visibility toggle and enhance the display of password requirements. Update styles for better usability and clarity.
> Enhance registration form usability and error handling

- royal-care-frontend/src/components/MainLayout.jsx
* Updated the text for the "Account" link to remove the placeholder comment.
* This change clarifies the link's purpose and improves user interface consistency.
> fix(MainLayout): ✏️ Remove placeholder text from "Account" link

- royal-care-frontend/src/pages/SalesReportsPage/SalesReportsPage.jsx
- royal-care-frontend/src/pages/SalesReportsPage/SalesReportsPage.module.css
* Added `date`, `day`, and `weekRange` fields to the commission data structure.
* Updated table headers to include `Date`, `Therapist`, and `Commission` for all periods.
* Adjusted table rows to display relevant data based on the selected `currentPeriod`.
* Ensured fallback values for missing data to enhance user experience.
> feat(SalesReportsPage): ✨ Update commission table structure for better data representation

- royal-care-frontend/package-lock.json
- royal-care-frontend/package.json
- royal-care-frontend/src/pages/SalesReportsPage/SalesReportsPage.jsx
- royal-care-frontend/src/pages/SalesReportsPage/SalesReportsPage.module.css
- Updated SalesReportsPage component to include export options for CSV, Excel, and PDF.
- Integrated file-saver, xlsx, and jsPDF libraries for file generation.
- Implemented dropdown menu for export options with appropriate styling.
- Enhanced data handling for different report views (Total Revenue, Commission, Customer List, Services).
- Added utility functions for converting data to CSV and generating Excel and PDF files.
- Styled export dropdown for better user experience.
> Add export functionality for sales reports with CSV, Excel, and PDF formats

- guitara/scheduling/views.py
- royal-care-frontend/src/components/scheduling/NotificationCenter.jsx
Add logic to exclude operator-only notifications for therapists and both operator and therapist notifications for drivers. Log filtered notifications count based on user role. Update NotificationCenter to fetch notifications with role-aware filtering.
> 🔧 Update NotificationViewSet to implement role-based filtering for notifications. 

- package-lock.json
- package.json
- royal-care-frontend/src/pages/InventoryPage/InventoryPage.jsx
- royal-care-frontend/src/pages/InventoryPage/InventoryPage.module.css
- royal-care-frontend/src/pages/InventoryPage/MUISelect.js
- Added @mui/material and @emotion dependencies to package.json.
- Replaced native select elements with MUI Select and MenuItem components in InventoryPage.
- Updated styles for the new MUI Select components to maintain UI consistency.
- Removed unnecessary padding from InventoryPage module CSS.
- Created a new MUISelect.js file to export MUI Select and MenuItem for reuse.
> feat: integrate MUI components for category selection in InventoryPage

- guitara/registration/views.py
- royal-care-frontend/src/hooks/useSettingsData.js
- royal-care-frontend/src/pages/SettingsDataPage/SettingsDataPage.jsx
- royal-care-frontend/src/services/api.js
Add pagination support to therapist, driver, operator, client, material, and service registration endpoints. Enhance data retrieval by including phone numbers associated with each user.
> Implement pagination and phone number fetching for registration endpoints

- royal-care-frontend/package-lock.json
- royal-care-frontend/package.json
- royal-care-frontend/src/components/scheduling/SchedulingDashboard.jsx
- royal-care-frontend/src/hooks/useDataManager.js
- royal-care-frontend/src/hooks/usePerformanceOptimization.js
- royal-care-frontend/src/hooks/useSettingsData.js
- royal-care-frontend/src/services/dataManager.js
- royal-care-frontend/vite.config.js
- Update useOptimizedSelector to ensure stable references and prevent selector warnings. 
- Update useDataManager for optimized memory management and performance tracking. 
- Update useSettingsData to log fetch times with a higher threshold. 
- Update DataManager for improved memory efficiency and reduced warning frequency.
> ✨ Add @emotion/react and @emotion/styled dependencies. Update Vite config to deduplicate Emotion packages. 

- DATA_MANAGER_OPTIMIZATION_GUIDE.md
- OPTIMIZATION_IMPLEMENTATION_STATUS.md
- royal-care-frontend/src/components/DriverDashboard.jsx
- royal-care-frontend/src/components/OperatorDashboard.jsx
- royal-care-frontend/src/components/TherapistDashboard.jsx
- royal-care-frontend/src/components/scheduling/SchedulingDashboard.jsx
- royal-care-frontend/src/hooks/useDashboardIntegration.js
- royal-care-frontend/src/hooks/useImmediateData.js
- royal-care-frontend/src/hooks/useOptimizedData.js
- royal-care-frontend/src/services/optimizedDataManager.js
- Replaced old data hooks with optimized versions in SchedulingDashboard.jsx.
- Simplified loading indicators and error handling across all dashboard components.
- Removed redundant polling and auto-refresh logic, leveraging the optimized data manager.
- Updated appointment handling functions to use centralized refresh methods.
- Enhanced performance by reducing API calls and memory usage.
- Documented migration status and performance benefits in OPTIMIZATION_IMPLEMENTATION_STATUS.md.
> Refactor Scheduling Dashboard and Related Hooks for Optimization

- royal-care-frontend/src/components/scheduling/AvailabilityManager.jsx
- royal-care-frontend/src/features/scheduling/schedulingSlice.js
- royal-care-frontend/src/utils/serviceHealthCheck.js
- royal-care-frontend/src/utils/serviceWorkerErrorSuppression.js
- Warn users about unusual end times and prevent problematic time ranges. 
- Update health check logic to consider migrated services as healthy. 
- Suppress additional service worker error messages related to health checks.
> 🔧 Add validation for cross-day availability in *AvailabilityManager* and *schedulingSlice*.

- Dockerfile
- docker-compose.yml
- guitara/guitara/settings.py
- guitara/guitara/settings_docker.py
- guitara/guitara/settings_production.py
- guitara/guitara/settings_railway.py
- guitara/scheduling/consumers.py
- guitara/scheduling/signals.py
- guitara/scheduling/websocket_handlers.py
- requirements.txt
- start_realtime_dev.py
- test_realtime_performance.py
- test_redis_connection.py
- Added Redis cache configuration to settings for Docker, Production, and Railway environments.
- Enhanced AppointmentConsumer to handle subscription requests and send initial data.
- Created a new websocket_handlers module to manage appointment and notification broadcasts.
- Updated signals to handle appointment creation, updates, deletions, and therapist responses with real-time notifications.
- Added performance testing scripts for WebSocket connections and API endpoint performance.
- Introduced a development startup script to streamline the setup of Redis, Django, and the frontend.
> Implement Redis caching for Django settings and enhance WebSocket handling

- royal-care-frontend/src/components/common/LazyClientSearch.jsx
- royal-care-frontend/src/components/scheduling/AppointmentFormTanStackComplete.jsx
- royal-care-frontend/src/components/scheduling/SchedulingDashboard.jsx
- royal-care-frontend/src/components/scheduling/WeekView.jsx
- royal-care-frontend/src/globals/FormField.jsx
- royal-care-frontend/src/styles/WeekView.css
- royal-care-frontend/src/styles/WeekViewEnhanced.css
- royal-care-frontend/src/utils/appointmentFormPersistence.js
- Added `AppointmentFormMigrated.module.css` for styling.
- Introduced time option generation for appointment scheduling (13:00 to 01:00).
- Implemented time validation to restrict appointment times within allowed windows.
- Enhanced appointment form with auto-save functionality using localStorage.
- Added client registration modal with form handling and state management.
- Updated `SchedulingDashboard` to manage view state and close forms appropriately.
- Enhanced `WeekView` to support multiple overlapping appointments with improved styling.
- Created `FormField` component for consistent form input handling.
- Added utility functions for appointment form data persistence (save, load, clear).
- Introduced enhanced styles for `WeekView` to improve appointment visibility and layout.
> feat: Implement appointment form persistence and enhanced scheduling features

- royal-care-frontend/src/components/DriverDashboard.jsx
- royal-care-frontend/src/components/MainLayout.jsx
- royal-care-frontend/src/components/OperatorDashboard.jsx
- royal-care-frontend/src/components/TherapistDashboard.jsx
- royal-care-frontend/src/hooks/useDashboardCommon.js
- royal-care-frontend/src/hooks/useModalState.js
- royal-care-frontend/src/hooks/usePhilippineTime.js
- royal-care-frontend/src/lib/queryClient.js
- royal-care-frontend/src/pages/InventoryPage/InventoryPage.jsx
- royal-care-frontend/src/pages/InventoryPage/InventoryPage.module.css
- royal-care-frontend/src/styles/OperatorDashboard.css
- royal-care-frontend/src/utils/userUtils.js
Introduce a material modal for therapists to verify materials before payment requests. Refactor state management and CSS for better maintainability. Consolidate dashboard logic into common hooks and update user display name handling for clarity. Implement inventory management features to ensure accurate stock levels after appointments.
> Enhance therapist dashboard with material modal and inventory management improvements

- guitara/authentication/serializers.py
- guitara/guitara/settings.py
- guitara/registration/serializers.py
- guitara/registration/views.py
- guitara/settings.py
- royal-care-frontend/README.md
- royal-care-frontend/package-lock.json
- royal-care-frontend/package.json
- royal-care-frontend/src/components/OperatorDashboard.jsx
- royal-care-frontend/src/components/auth/Register.jsx
- royal-care-frontend/src/globals/FormField.jsx
- royal-care-frontend/src/pages/2FAForgotPasswordPage/TwoFAForgotPasswordPage.jsx
- royal-care-frontend/src/pages/EmailVerificationPage/EmailVerificationPage.jsx
- royal-care-frontend/src/pages/EmailVerificationPage/EmailVerificationPage.module.css
- royal-care-frontend/src/pages/ForgotPasswordPage/ForgotPasswordPage.jsx
- royal-care-frontend/src/pages/LoginPage/LoginPage.jsx
- start_backend.bat
- start_development.py
Improve form validation logic across registration and login forms, enhance email validation with immediate backend error display, and refine user feedback for email verification. Update package dependencies and backend scripts for better performance and clarity.
> Update form validation and enhance email verification flow
